export const transparency = {
    'tran.title':'Transparency Demonstration Tool',
    'tran.subTitle':'Demonstrate your organization\'s transparency practices with our comprehensive assessment platform. Build trust, demonstrate accountability, and identify areas for improvement.',
    'tran.build':'Build Trust & Credibility',
    'tran.demon':'Demonstrate your commitment to openness and accountability to the public.',   
    'tran.identify':'Identify Improvements',
    'tran.action':' Get actionable insights and personalized recommendations to enhance your transparency practices.',
    'tran.download':'Downloadable Reports',
    'tran.report':' Receive comprehensive reports with detailed analysis and benchmarking data.',
    'tran.work':'How It Works',

    'tran.startProcess':'Start Demonstation process',
    'tran.ans':'Answer Questions',
    'tran.score':'Get Scored',
    'tran.downloadReport':'Download Report',

    'tran.desc1':'Click to begin your transparency evaluation',
    'tran.desc2':'Complete multi-part questions about your practices',
    'tran.desc3':'Receive real-time scoring and progress tracking',
    'tran.desc4':'Get detailed results and recommendations',

    'tran.readyToAccess':'Ready to Assess Your Transparency?',
    'tran.takeAstep':' Take the first step towards building greater trust and accountability in your organization and in the public.',

    'tran.organization':'Organization',
    'tran.questions':'Questions',
    'tran.results':'Results',

    'tran.planned':'planned',
    'tran.ongoing':'ongoing',
    'tran.completed':'completed',

    'tran.demonstration':'Transparency Demonstration',
    'tran.demonstration2':'Demonstration of Transparency Practices',

    'tran.why':'Why This  Matters',
    'tran.quick':'Quick & Comprehensive',
    'tran.time':'Takes only 30-45 minutes to complete with immediate results and downloadable report',

    'tran.youGet':'What You\'ll Get',
    'tran.bullet1':'Comprehensive transparency score and analysis',
    'tran.bullet2':'Personalized recommendations for improvement',
    'tran.bullet3':'Downloadable report for your records',

    'tran.comprehensive':'Complete this comprehensive form to evaluate your organization\'s transparency practices',

    'tran.of':'of',
    'tran.nextQuestion':'Next Question',
    'tran.excellent':'Excellent',
    'tran.good':'Good',
    'tran.Improvement':'Needs Improvement',

    'tran.skipped':'Skipped',
    'tran.yes':'Yes',
     'tran.no':'No',
     'tran.notAnswered':'Not Answered',
     'tran.noneSelected':'None Selected',
     'tran.noFile':'No File Uploaded',

    'tran.recommendation1':'Consider developing a comprehensive transparency strategy',
    'tran.recommendation2':'Establish regular reporting mechanisms for key metrics',
    'tran.recommendation3':'Enhance stakeholder communication channels',
    'tran.recommendation4':'Implement more robust documentation practices',
    'tran.addressing':'Consider addressing',
    'tran.practices':'practices',
    'tran.strengthen':'Strengthen your',

     'tran.demonstrationReport':'TRANSPARENCY DEMONSTRATION REPORT',
     'tran.generated':'Generated on',

     'tran.orgInfo':'ORGANIZATION INFORMATION',
     'tran.orgName':'Organization Name',
     'tran.orgType':'Organization Type',
     'tran.orgGoal':'Organization Goal',
     'tran.notSpecified':'Not specified',
     'tran.orgDescription':'Organization Description',
     'tran.NoOrgDescription':'No description provided',

     'tran.overallResults':'OVERALL RESULTS',
     'tran.Rscore':'Score',
     'tran.category':'Category',

    'tran.responses':'DETAILED RESPONSES',
    'tran.answer':'Answer',
    'tran.selectedOptions':'Selected Options',
    'tran.uploadedFile':'File Upload',

    'tran.recommendation':'RECOMMENDATIONS',
    'trans.recoDesc':'This report was generated by the Transparency Assessment Tool. For more information on improving your transparency practices, consult with governance and compliance experts.'
,
    'tran.assessment':'transparency-assessment',
    'tran.downloadedReport':'Report Downloaded',
    'tran.downloadDesc':'Your transparency assessment report has been downloaded successfully.',

    'tran.tranResults':' Your Transparency Results',
    'tran.formFilled':' Form filled  on',
    
    'tran.questionCompleted':'Questions Completed',
    'tran.questionSkipped':'Questions Skipped',
    'tran.filesUploaded':'Files Uploaded',
    'tran.questionBreakdown':'Question Breakdown',
    'tran.questionNotAnswered':'Question Not Answered',

    'tran.closeResults':'Close Results',
    'tran.yourScore':'Your Score',
    'tran.progess':'Progess',

    'tran.backOrg':'Back to Organization Info',
    'tran.prev':'Previous',

    //Questions
    'tran.fileType':'Invalid file type',
    'tran.upload':'Please upload an image, PDF, or Word document.',
    'tran.largeUploadError':'File too large',
    'tran.largeUploadErrorDesc':'Please upload a file smaller than 10MB.',
    'tran.uploadSuccess':'File uploaded successfully',
    'tran.uploaded':'has been uploaded',
    'tran.skipQuestion':'Skip Question',
    'tran.remove':'Remove',
    'tran.drag-drop':' Drag and drop your file here, or click to browse',
    'tran.supprt':'Support',
    'tran.chooseFile':'Choose File',
    'tran.skippedText':' This question has been skipped and won\'t contribute to your final score.',
    'tran.answerQuestion':'Answer This Question',





}